# Generated by Django 6.1 on 2026-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес локации')),
                ('landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ориентир')),
                ('map_link', models.URLField(max_length=500, verbose_name='Ссылка на карту (Yandex/Google Maps)')),
                ('photo', models.ImageField(upload_to='branches/photos/', verbose_name='Фотография филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
    ]
